### ISSUE TITLE
ZohoSalesIQ.Chat.show() not working on the first click

### ISSUE THREAD

**Issue by AlirezaDaryani** [zoho/salesiq-mobilisten-android-sample#28]
I implemented your SDK in my app and i handle open chat in some button with below code:

            ZohoSalesIQ.registerVisitor(id);
            ZohoSalesIQ.Visitor.setEmail(email);
            ZohoSalesIQ.Visitor.setName(name);
            ZohoSalesIQ.Visitor.setContactNumber(phone);
            ZohoSalesIQ.Chat.show();

I inited `ZohoSalesIQ` in Application class.

Now when user click on button, for first time nothing happen and in second click, chat open properly .

Someone help me on this pls
Why button not work for first touch?

**Comment by AlirezaDaryani** [comment]
Invalid ID 0x00000000.

This printed in log after first click...

**Comment by Angu-G** [comment]
@AlirezaDaryani , Can you please try **.show()** API in separate click event. Because *Invalid ID* exception should be thrown from .registerVisitor() API.

**Comment by Angu-G** [comment]
Hello @AlirezaDaryani, We would like to bring you one more suggestion here.
The **.registerVisitor()** API can be used in the login cycle because SDK data will be reinitialized here once you make a call. so any API that is immediately triggered following this API might misbehave.

Also using .show() API alone in the button click from where you try to open SDK would be advisable.

Please do confirm us whether this issue get resolved?

**Comment by AlirezaDaryani** [comment]
@Angu-G 
Hi, this help me and i wrote separate function for .show() method and problem fixed.
Thanks.

**Comment by Angu-G** [comment]
Thanks, @AlirezaDaryani. Closing the issue.
