### ISSUE TITLE
- Which property to set fixed orientation like portrait and landscape? ex:  android:screenOrientation="portrait"

### ISSUE THREAD

**Issue by JackeyPSSPL** [zoho/salesiq-mobilisten-android-sample#41]
- Which property to set fixed orientation like portrait and landscape? ex:  android:screenOrientation="portrait"

**Comment by DavidBhahirathan** [comment]
Hi @JackeyPSSPL, 

Thank you for reaching out to us regarding the issue. We apologize for the inconvenience caused.

We'll look into this issue and update you here. 

Thanks,
Bhahirathan M
Zoho SalesIQ.

**Comment by DavidBhahirathan** [comment]
Hi @JackeyPSSPL ,

Thanks for your patience. Due to some limitations in Android, we are not able to provide a specific API for screen orientation from Mobilisten Android SDK. So, please add the below code inside the <application> ... </application> in your AndroidManifest file.

AndroidManifest.xml
```
<activity
    android:name="com.zoho.livechat.android.ui.activities.SalesIQActivity"
    android:screenOrientation="portrait" />
<activity
    android:name="com.zoho.livechat.android.ui.activities.ChatActivity"
    android:screenOrientation="portrait" />
<activity
    android:name="com.zoho.livechat.android.ViewBotCardImageActivity"
    android:screenOrientation="portrait" />
<activity
    android:name="com.zoho.livechat.android.ui.activities.ArticlesActivity"
    android:screenOrientation="portrait" />
```

I hope this helps. If the issue persists, please don't hesitate to contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Bhahirathan M
Zoho SalesIQ.
